### ISSUE TITLE
chapter05_td中“Taxi-v3.ipynb”的计算方式和书上的讲解不完全相符

### ISSUE THREAD

**Issue by A-Pai** [ZhiqingXiao/rl-book#11]
chapter05_td中“Taxi-v3.ipynb”的这种计算方式：
![image](https://user-images.githubusercontent.com/5112397/129355141-2376a900-a0fe-4ea7-bd01-e7fc5f822ae8.png)
和书上的讲解不完全相符：
![image](https://user-images.githubusercontent.com/5112397/129355653-0619883f-cccf-41b5-9a51-6d0c6b966dad.png)
是这样吗？还是我没有更新？

另外“self.q[next_state].mean()”也不是按照策略计算均值：
![image](https://user-images.githubusercontent.com/5112397/129356541-50400078-0507-444c-b9e8-6bc209a01c98.png)

**Comment by ZhiqingXiao** [comment]
这里的策略π以1-ε的概率选择最优动作，以ε的概率选择随机动作。
将π的表达式代入用t时刻的动作价值表示t时刻的状态价值的关系v=Σ π(a|s) q(s,a)可得v(s)=[mean q(s,a)]ε+\[max q(s,a)](1-ε)。
