### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by jupitermarketingagency** [ZhiqingXiao/rl-book#14]
I'm getting the following error when running the Advantage Actor-Critic to Play Acrobot-V1

ValueError                                Traceback (most recent call last)
[<ipython-input-22-c44611e633a7>](https://localhost:8080/#) in <cell line: 21>()
     20 episode_rewards = []
     21 for episode in itertools.count():
---> 22     episode_reward, elapsed_steps = play_episode(env, agent, seed=episode,
     23             mode='train')
     24     episode_rewards.append(episode_reward)

[<ipython-input-22-c44611e633a7>](https://localhost:8080/#) in play_episode(env, agent, seed, mode, render)
      1 def play_episode(env, agent, seed=None, mode=None, render=False):
----> 2     observation, _ = env.reset(seed=seed)
      3     reward, terminated, truncated = 0., False, False
      4     agent.reset(mode=mode)
      5     episode_reward, elapsed_steps = 0., 0

ValueError: too many values to unpack (expected 2)

**Comment by ZhiqingXiao** [comment]
Please update Gym to the latest version (i.e. Gym 0.26.2).
