### ISSUE TITLE
第六章MoutainCar-v0 砖瓦编码计算的问题

### ISSUE THREAD

**Issue by lwzswufe** [ZhiqingXiao/rl-book#3]
在 class TileCoder 里的__call__(）
    def __call__(self, floats=(), ints=()):
        dim = len(floats)
        scaled_floats = tuple(f * self.layers * self.layers for f in floats)
        features = []
        for layer in range(self.layers):
            codeword = (layer,) + tuple(int((f + (1 + dim * i) * layer) /
                    self.layers) for i, f in enumerate(scaled_floats)) + ints
            feature = self.get_feature(codeword)
            features.append(feature)
        return features
这里使用了 (f + (1 + dim * i) * layer) 来计算不同layer的位置
但是实际计算， 当i=1时 会把1-7层的的坐标映射到1-9或2-10
实测表明 使用(f + layer) 效果会更好 而且会严格的把1-7层的数据映射到0-8
>>>>>>>>>>>>>>>>>>>>SARSA 算法<<<<<<<<<<<<<<<<<<<<<
平均回合奖励 = -12649.0 / 100 = -126.49
>>>>>>>>>>>>>>>>>>>>SARSA(λ) 算法<<<<<<<<<<<<<<<<<<<<<
平均回合奖励 = -10181.0 / 100 = -101.81
我们为什么要采用(f + (1 + dim * i) * layer) 来计算呢？

**Comment by ZhiqingXiao** [comment]
这里用了asymmetric tile codings，每个维度的偏移量都不同。
对于第i个维度每层的偏移量为1+总维数*i，其中1保证有偏移。
