### ISSUE TITLE
书本第二章线性规划求解最优状态价值

### ISSUE THREAD

**Issue by ZhengYuNing8988** [ZhiqingXiao/rl-book#4]
请问一下书本第二章线性规划求解最优状态价值中：minimize、over、s.t.各代表什么啊，书本并没有说明，网上也没有类似这样的表达

**Comment by ylzf0000** [comment]
请问你是哪位？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhengYuNing8988"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 晚上11:04
收件人:&nbsp;"ZhiqingXiao/rl-book"<rl-book@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ZhiqingXiao/rl-book] 书本第二章线性规划求解最优状态价值 (#4)




请问一下书本第二章线性规划求解最优状态价值中：minimize、over、s.t.各代表什么啊，书本并没有说明，网上也没有类似这样的表达

**Comment by ylzf0000** [comment]
s.t. 就是 subject to，服从于以下条件的意思
minimize是最小化
over在哪，我没看见


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhengYuNing8988"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 晚上11:04
收件人:&nbsp;"ZhiqingXiao/rl-book"<rl-book@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ZhiqingXiao/rl-book] 书本第二章线性规划求解最优状态价值 (#4)




请问一下书本第二章线性规划求解最优状态价值中：minimize、over、s.t.各代表什么啊，书本并没有说明，网上也没有类似这样的表达

**Comment by ZhiqingXiao** [comment]
minimize 对优化目标最小化
maximize 对优化目标最大化
over 决策变量
s.t. 约束条件

@ylzf0000 谢谢解答。
