### ISSUE TITLE
我购买了kindle电子书，勘误太多了，感觉几页就是一个错误，能够提供修改的电子版？

### ISSUE THREAD

**Issue by erichuazhou** [ZhiqingXiao/rl-book#6]
我太服气了，这么多错误。要一边看电子版一边看勘误。牛。

**Comment by ZhiqingXiao** [comment]
谢谢反馈。我无法提供电子版勘误（我不知道你的电子版勘误哪里来的），也无法提供修改后的电子版。

**Comment by erichuazhou** [comment]
能不能联系下amazon，把kindle电子书更新下。谢谢.

**Comment by erichuazhou** [comment]
@ZhiqingXiao

**Comment by ZhiqingXiao** [comment]
@erichuazhou 我曾经试图让出版社帮忙改电子版，但是失败了。如果您知道如何更新kindle电子书，请分享给我，谢谢。
（实际上我自己并没有买过或用过kindle，也没有看过任何kindle电子书，只能从kindle的广告和其他kindle用户的描述中猜测kindle电子书是什么。）
